// 省 -> 市 -> 区县 三级行政区数据
// 叶节点 cityKey 对应 CITY_LONGITUDE 中的城市名（用于真太阳时经度查找）

export interface District {
  name: string;
  cityKey: string; // 映射到 CITY_LONGITUDE 的城市名
}

export interface City {
  name: string;
  districts: District[];
}

export interface Province {
  name: string;
  cities: City[];
}

export const REGION_DATA: Province[] = [
  {
    name: '北京市',
    cities: [
      {
        name: '北京市',
        districts: [
          { name: '东城区', cityKey: '北京' },
          { name: '西城区', cityKey: '北京' },
          { name: '朝阳区', cityKey: '北京' },
          { name: '海淀区', cityKey: '北京' },
          { name: '丰台区', cityKey: '北京' },
          { name: '石景山区', cityKey: '北京' },
          { name: '门头沟区', cityKey: '北京' },
          { name: '房山区', cityKey: '北京' },
          { name: '通州区', cityKey: '北京' },
          { name: '顺义区', cityKey: '北京' },
          { name: '昌平区', cityKey: '北京' },
          { name: '大兴区', cityKey: '北京' },
          { name: '怀柔区', cityKey: '北京' },
          { name: '平谷区', cityKey: '北京' },
          { name: '密云区', cityKey: '北京' },
          { name: '延庆区', cityKey: '北京' },
        ],
      },
    ],
  },
  {
    name: '天津市',
    cities: [
      {
        name: '天津市',
        districts: [
          { name: '和平区', cityKey: '天津' },
          { name: '河东区', cityKey: '天津' },
          { name: '河西区', cityKey: '天津' },
          { name: '南开区', cityKey: '天津' },
          { name: '河北区', cityKey: '天津' },
          { name: '红桥区', cityKey: '天津' },
          { name: '滨海新区', cityKey: '天津' },
          { name: '东丽区', cityKey: '天津' },
          { name: '西青区', cityKey: '天津' },
          { name: '津南区', cityKey: '天津' },
          { name: '北辰区', cityKey: '天津' },
          { name: '武清区', cityKey: '天津' },
          { name: '宝坻区', cityKey: '天津' },
          { name: '宁河区', cityKey: '天津' },
          { name: '静海区', cityKey: '天津' },
          { name: '蓟州区', cityKey: '天津' },
        ],
      },
    ],
  },
  {
    name: '上海市',
    cities: [
      {
        name: '上海市',
        districts: [
          { name: '黄浦区', cityKey: '上海' },
          { name: '徐汇区', cityKey: '上海' },
          { name: '长宁区', cityKey: '上海' },
          { name: '静安区', cityKey: '上海' },
          { name: '普陀区', cityKey: '上海' },
          { name: '虹口区', cityKey: '上海' },
          { name: '杨浦区', cityKey: '上海' },
          { name: '浦东新区', cityKey: '上海' },
          { name: '闵行区', cityKey: '上海' },
          { name: '宝山区', cityKey: '上海' },
          { name: '嘉定区', cityKey: '上海' },
          { name: '金山区', cityKey: '上海' },
          { name: '松江区', cityKey: '上海' },
          { name: '青浦区', cityKey: '上海' },
          { name: '奉贤区', cityKey: '上海' },
          { name: '崇明区', cityKey: '上海' },
        ],
      },
    ],
  },
  {
    name: '重庆市',
    cities: [
      {
        name: '重庆市',
        districts: [
          { name: '渝中区', cityKey: '重庆' },
          { name: '江北区', cityKey: '重庆' },
          { name: '沙坪坝区', cityKey: '重庆' },
          { name: '九龙坡区', cityKey: '重庆' },
          { name: '南岸区', cityKey: '重庆' },
          { name: '北碚区', cityKey: '重庆' },
          { name: '渝北区', cityKey: '重庆' },
          { name: '巴南区', cityKey: '重庆' },
          { name: '长寿区', cityKey: '重庆' },
          { name: '江津区', cityKey: '重庆' },
          { name: '合川区', cityKey: '重庆' },
          { name: '永川区', cityKey: '重庆' },
          { name: '綦江区', cityKey: '重庆' },
          { name: '大足区', cityKey: '重庆' },
          { name: '荣昌区', cityKey: '重庆' },
          { name: '铜梁区', cityKey: '重庆' },
        ],
      },
    ],
  },
  {
    name: '河北省',
    cities: [
      {
        name: '石家庄市',
        districts: [
          { name: '长安区', cityKey: '石家庄' },
          { name: '桥西区', cityKey: '石家庄' },
          { name: '新华区', cityKey: '石家庄' },
          { name: '裕华区', cityKey: '石家庄' },
          { name: '藁城区', cityKey: '石家庄' },
          { name: '鹿泉区', cityKey: '石家庄' },
          { name: '栾城区', cityKey: '石家庄' },
          { name: '井陉县', cityKey: '石家庄' },
          { name: '正定县', cityKey: '石家庄' },
          { name: '行唐县', cityKey: '石家庄' },
          { name: '灵寿县', cityKey: '石家庄' },
          { name: '赵县', cityKey: '石家庄' },
          { name: '辛集市', cityKey: '石家庄' },
          { name: '晋州市', cityKey: '石家庄' },
          { name: '新乐市', cityKey: '石家庄' },
        ],
      },
      {
        name: '唐山市',
        districts: [
          { name: '路南区', cityKey: '石家庄' },
          { name: '路北区', cityKey: '石家庄' },
          { name: '古冶区', cityKey: '石家庄' },
          { name: '开平区', cityKey: '石家庄' },
          { name: '丰南区', cityKey: '石家庄' },
          { name: '丰润区', cityKey: '石家庄' },
          { name: '曹妃甸区', cityKey: '石家庄' },
          { name: '滦州市', cityKey: '石家庄' },
          { name: '迁安市', cityKey: '石家庄' },
          { name: '遵化市', cityKey: '石家庄' },
          { name: '迁西县', cityKey: '石家庄' },
          { name: '玉田县', cityKey: '石家庄' },
        ],
      },
      {
        name: '秦皇岛市',
        districts: [
          { name: '海港区', cityKey: '石家庄' },
          { name: '山海关区', cityKey: '石家庄' },
          { name: '北戴河区', cityKey: '石家庄' },
          { name: '抚宁区', cityKey: '石家庄' },
          { name: '青龙满族自治县', cityKey: '石家庄' },
          { name: '昌黎县', cityKey: '石家庄' },
          { name: '卢龙县', cityKey: '石家庄' },
        ],
      },
      {
        name: '邯郸市',
        districts: [
          { name: '邯山区', cityKey: '石家庄' },
          { name: '丛台区', cityKey: '石家庄' },
          { name: '复兴区', cityKey: '石家庄' },
          { name: '峰峰矿区', cityKey: '石家庄' },
          { name: '肥乡区', cityKey: '石家庄' },
          { name: '永年区', cityKey: '石家庄' },
          { name: '临漳县', cityKey: '石家庄' },
          { name: '成安县', cityKey: '石家庄' },
          { name: '大名县', cityKey: '石家庄' },
          { name: '涉县', cityKey: '石家庄' },
          { name: '磁县', cityKey: '石家庄' },
          { name: '武安市', cityKey: '石家庄' },
        ],
      },
      {
        name: '邢台市',
        districts: [
          { name: '襄都区', cityKey: '石家庄' },
          { name: '信都区', cityKey: '石家庄' },
          { name: '任泽区', cityKey: '石家庄' },
          { name: '南和区', cityKey: '石家庄' },
          { name: '宁晋县', cityKey: '石家庄' },
          { name: '巨鹿县', cityKey: '石家庄' },
          { name: '威县', cityKey: '石家庄' },
          { name: '清河县', cityKey: '石家庄' },
          { name: '南宫市', cityKey: '石家庄' },
          { name: '沙河市', cityKey: '石家庄' },
        ],
      },
      {
        name: '保定市',
        districts: [
          { name: '竞秀区', cityKey: '石家庄' },
          { name: '莲池区', cityKey: '石家庄' },
          { name: '满城区', cityKey: '石家庄' },
          { name: '清苑区', cityKey: '石家庄' },
          { name: '徐水区', cityKey: '石家庄' },
          { name: '涞水县', cityKey: '石家庄' },
          { name: '阜平县', cityKey: '石家庄' },
          { name: '定兴县', cityKey: '石家庄' },
          { name: '唐县', cityKey: '石家庄' },
          { name: '容城县', cityKey: '石家庄' },
          { name: '易县', cityKey: '石家庄' },
          { name: '涿州市', cityKey: '石家庄' },
          { name: '定州市', cityKey: '石家庄' },
          { name: '安国市', cityKey: '石家庄' },
          { name: '高碑店市', cityKey: '石家庄' },
        ],
      },
      {
        name: '张家口市',
        districts: [
          { name: '桥东区', cityKey: '石家庄' },
          { name: '桥西区', cityKey: '石家庄' },
          { name: '宣化区', cityKey: '石家庄' },
          { name: '下花园区', cityKey: '石家庄' },
          { name: '万全区', cityKey: '石家庄' },
          { name: '崇礼区', cityKey: '石家庄' },
          { name: '张北县', cityKey: '石家庄' },
          { name: '蔚县', cityKey: '石家庄' },
          { name: '怀来县', cityKey: '石家庄' },
          { name: '涿鹿县', cityKey: '石家庄' },
          { name: '赤城县', cityKey: '石家庄' },
        ],
      },
      {
        name: '承德市',
        districts: [
          { name: '双桥区', cityKey: '石家庄' },
          { name: '双滦区', cityKey: '石家庄' },
          { name: '鹰手营子矿区', cityKey: '石家庄' },
          { name: '承德县', cityKey: '石家庄' },
          { name: '兴隆县', cityKey: '石家庄' },
          { name: '平泉市', cityKey: '石家庄' },
          { name: '滦平县', cityKey: '石家庄' },
          { name: '隆化县', cityKey: '石家庄' },
          { name: '丰宁满族自治县', cityKey: '石家庄' },
          { name: '宽城满族自治县', cityKey: '石家庄' },
          { name: '围场满族蒙古族自治县', cityKey: '石家庄' },
        ],
      },
      {
        name: '沧州市',
        districts: [
          { name: '新华区', cityKey: '石家庄' },
          { name: '运河区', cityKey: '石家庄' },
          { name: '沧县', cityKey: '石家庄' },
          { name: '青县', cityKey: '石家庄' },
          { name: '东光县', cityKey: '石家庄' },
          { name: '盐山县', cityKey: '石家庄' },
          { name: '肃宁县', cityKey: '石家庄' },
          { name: '南皮县', cityKey: '石家庄' },
          { name: '吴桥县', cityKey: '石家庄' },
          { name: '献县', cityKey: '石家庄' },
          { name: '任丘市', cityKey: '石家庄' },
          { name: '黄骅市', cityKey: '石家庄' },
          { name: '河间市', cityKey: '石家庄' },
        ],
      },
      {
        name: '廊坊市',
        districts: [
          { name: '安次区', cityKey: '石家庄' },
          { name: '广阳区', cityKey: '石家庄' },
          { name: '固安县', cityKey: '石家庄' },
          { name: '永清县', cityKey: '石家庄' },
          { name: '香河县', cityKey: '石家庄' },
          { name: '大城县', cityKey: '石家庄' },
          { name: '文安县', cityKey: '石家庄' },
          { name: '大厂回族自治县', cityKey: '石家庄' },
          { name: '霸州市', cityKey: '石家庄' },
          { name: '三河市', cityKey: '石家庄' },
        ],
      },
      {
        name: '衡水市',
        districts: [
          { name: '桃城区', cityKey: '石家庄' },
          { name: '冀州区', cityKey: '石家庄' },
          { name: '枣强县', cityKey: '石家庄' },
          { name: '武邑县', cityKey: '石家庄' },
          { name: '武强县', cityKey: '石家庄' },
          { name: '饶阳县', cityKey: '石家庄' },
          { name: '安平县', cityKey: '石家庄' },
          { name: '故城县', cityKey: '石家庄' },
          { name: '景县', cityKey: '石家庄' },
          { name: '阜城县', cityKey: '石家庄' },
          { name: '深州市', cityKey: '石家庄' },
        ],
      },
    ],
  },
  {
    name: '山西省',
    cities: [
      {
        name: '太原市',
        districts: [
          { name: '小店区', cityKey: '太原' },
          { name: '迎泽区', cityKey: '太原' },
          { name: '杏花岭区', cityKey: '太原' },
          { name: '尖草坪区', cityKey: '太原' },
          { name: '万柏林区', cityKey: '太原' },
          { name: '晋源区', cityKey: '太原' },
          { name: '清徐县', cityKey: '太原' },
          { name: '阳曲县', cityKey: '太原' },
          { name: '娄烦县', cityKey: '太原' },
          { name: '古交市', cityKey: '太原' },
        ],
      },
      {
        name: '大同市',
        districts: [
          { name: '平城区', cityKey: '太原' },
          { name: '云冈区', cityKey: '太原' },
          { name: '云州区', cityKey: '太原' },
          { name: '阳高县', cityKey: '太原' },
          { name: '天镇县', cityKey: '太原' },
          { name: '广灵县', cityKey: '太原' },
          { name: '灵丘县', cityKey: '太原' },
          { name: '浑源县', cityKey: '太原' },
          { name: '左云县', cityKey: '太原' },
        ],
      },
      {
        name: '朔州市',
        districts: [
          { name: '朔城区', cityKey: '太原' },
          { name: '平鲁区', cityKey: '太原' },
          { name: '山阴县', cityKey: '太原' },
          { name: '应县', cityKey: '太原' },
          { name: '右玉县', cityKey: '太原' },
          { name: '怀仁市', cityKey: '太原' },
        ],
      },
      {
        name: '忻州市',
        districts: [
          { name: '忻府区', cityKey: '太原' },
          { name: '定襄县', cityKey: '太原' },
          { name: '五台县', cityKey: '太原' },
          { name: '代县', cityKey: '太原' },
          { name: '繁峙县', cityKey: '太原' },
          { name: '宁武县', cityKey: '太原' },
          { name: '静乐县', cityKey: '太原' },
          { name: '神池县', cityKey: '太原' },
          { name: '五寨县', cityKey: '太原' },
          { name: '河曲县', cityKey: '太原' },
          { name: '保德县', cityKey: '太原' },
          { name: '偏关县', cityKey: '太原' },
          { name: '原平市', cityKey: '太原' },
        ],
      },
      {
        name: '吕梁市',
        districts: [
          { name: '离石区', cityKey: '太原' },
          { name: '文水县', cityKey: '太原' },
          { name: '交城县', cityKey: '太原' },
          { name: '兴县', cityKey: '太原' },
          { name: '临县', cityKey: '太原' },
          { name: '柳林县', cityKey: '太原' },
          { name: '石楼县', cityKey: '太原' },
          { name: '岚县', cityKey: '太原' },
          { name: '方山县', cityKey: '太原' },
          { name: '中阳县', cityKey: '太原' },
          { name: '孝义市', cityKey: '太原' },
          { name: '汾阳市', cityKey: '太原' },
        ],
      },
      {
        name: '晋中市',
        districts: [
          { name: '榆次区', cityKey: '太原' },
          { name: '太谷区', cityKey: '太原' },
          { name: '榆社县', cityKey: '太原' },
          { name: '左权县', cityKey: '太原' },
          { name: '和顺县', cityKey: '太原' },
          { name: '昔阳县', cityKey: '太原' },
          { name: '寿阳县', cityKey: '太原' },
          { name: '祁县', cityKey: '太原' },
          { name: '平遥县', cityKey: '太原' },
          { name: '灵石县', cityKey: '太原' },
          { name: '介休市', cityKey: '太原' },
        ],
      },
      {
        name: '阳泉市',
        districts: [
          { name: '城区', cityKey: '太原' },
          { name: '矿区', cityKey: '太原' },
          { name: '郊区', cityKey: '太原' },
          { name: '平定县', cityKey: '太原' },
          { name: '盂县', cityKey: '太原' },
        ],
      },
      {
        name: '长治市',
        districts: [
          { name: '潞州区', cityKey: '太原' },
          { name: '上党区', cityKey: '太原' },
          { name: '屯留区', cityKey: '太原' },
          { name: '潞城区', cityKey: '太原' },
          { name: '襄垣县', cityKey: '太原' },
          { name: '平顺县', cityKey: '太原' },
          { name: '黎城县', cityKey: '太原' },
          { name: '壶关县', cityKey: '太原' },
          { name: '长子县', cityKey: '太原' },
          { name: '武乡县', cityKey: '太原' },
          { name: '沁县', cityKey: '太原' },
          { name: '沁源县', cityKey: '太原' },
        ],
      },
      {
        name: '晋城市',
        districts: [
          { name: '城区', cityKey: '太原' },
          { name: '沁水县', cityKey: '太原' },
          { name: '阳城县', cityKey: '太原' },
          { name: '陵川县', cityKey: '太原' },
          { name: '泽州县', cityKey: '太原' },
          { name: '高平市', cityKey: '太原' },
        ],
      },
      {
        name: '运城市',
        districts: [
          { name: '盐湖区', cityKey: '太原' },
          { name: '临猗县', cityKey: '太原' },
          { name: '万荣县', cityKey: '太原' },
          { name: '闻喜县', cityKey: '太原' },
          { name: '稷山县', cityKey: '太原' },
          { name: '新绛县', cityKey: '太原' },
          { name: '绛县', cityKey: '太原' },
          { name: '垣曲县', cityKey: '太原' },
          { name: '夏县', cityKey: '太原' },
          { name: '平陆县', cityKey: '太原' },
          { name: '芮城县', cityKey: '太原' },
          { name: '永济市', cityKey: '太原' },
          { name: '河津市', cityKey: '太原' },
        ],
      },
      {
        name: '临汾市',
        districts: [
          { name: '尧都区', cityKey: '太原' },
          { name: '曲沃县', cityKey: '太原' },
          { name: '翼城县', cityKey: '太原' },
          { name: '襄汾县', cityKey: '太原' },
          { name: '洪洞县', cityKey: '太原' },
          { name: '古县', cityKey: '太原' },
          { name: '安泽县', cityKey: '太原' },
          { name: '浮山县', cityKey: '太原' },
          { name: '吉县', cityKey: '太原' },
          { name: '乡宁县', cityKey: '太原' },
          { name: '大宁县', cityKey: '太原' },
          { name: '隰县', cityKey: '太原' },
          { name: '永和县', cityKey: '太原' },
          { name: '蒲县', cityKey: '太原' },
          { name: '汾西县', cityKey: '太原' },
          { name: '侯马市', cityKey: '太原' },
          { name: '霍州市', cityKey: '太原' },
        ],
      },
    ],
  },
  {
    name: '辽宁省',
    cities: [
      {
        name: '沈阳市',
        districts: [
          { name: '和平区', cityKey: '沈阳' },
          { name: '沈河区', cityKey: '沈阳' },
          { name: '大东区', cityKey: '沈阳' },
          { name: '皇姑区', cityKey: '沈阳' },
          { name: '铁西区', cityKey: '沈阳' },
          { name: '苏家屯区', cityKey: '沈阳' },
          { name: '浑南区', cityKey: '沈阳' },
          { name: '沈北新区', cityKey: '沈阳' },
          { name: '于洪区', cityKey: '沈阳' },
          { name: '辽中区', cityKey: '沈阳' },
          { name: '康平县', cityKey: '沈阳' },
          { name: '法库县', cityKey: '沈阳' },
          { name: '新民市', cityKey: '沈阳' },
        ],
      },
      {
        name: '大连市',
        districts: [
          { name: '中山区', cityKey: '沈阳' },
          { name: '西岗区', cityKey: '沈阳' },
          { name: '沙河口区', cityKey: '沈阳' },
          { name: '甘井子区', cityKey: '沈阳' },
          { name: '旅顺口区', cityKey: '沈阳' },
          { name: '金州区', cityKey: '沈阳' },
          { name: '普兰店区', cityKey: '沈阳' },
          { name: '长海县', cityKey: '沈阳' },
          { name: '瓦房店市', cityKey: '沈阳' },
          { name: '庄河市', cityKey: '沈阳' },
        ],
      },
      {
        name: '鞍山市',
        districts: [
          { name: '铁东区', cityKey: '沈阳' },
          { name: '铁西区', cityKey: '沈阳' },
          { name: '立山区', cityKey: '沈阳' },
          { name: '千山区', cityKey: '沈阳' },
          { name: '台安县', cityKey: '沈阳' },
          { name: '岫岩满族自治县', cityKey: '沈阳' },
          { name: '海城市', cityKey: '沈阳' },
        ],
      },
      {
        name: '抚顺市',
        districts: [
          { name: '新抚区', cityKey: '沈阳' },
          { name: '东洲区', cityKey: '沈阳' },
          { name: '望花区', cityKey: '沈阳' },
          { name: '顺城区', cityKey: '沈阳' },
          { name: '抚顺县', cityKey: '沈阳' },
          { name: '新宾满族自治县', cityKey: '沈阳' },
          { name: '清原满族自治县', cityKey: '沈阳' },
        ],
      },
      {
        name: '本溪市',
        districts: [
          { name: '平山区', cityKey: '沈阳' },
          { name: '溪湖区', cityKey: '沈阳' },
          { name: '明山区', cityKey: '沈阳' },
          { name: '南芬区', cityKey: '沈阳' },
          { name: '本溪满族自治县', cityKey: '沈阳' },
          { name: '桓仁满族自治县', cityKey: '沈阳' },
        ],
      },
      {
        name: '丹东市',
        districts: [
          { name: '元宝区', cityKey: '沈阳' },
          { name: '振兴区', cityKey: '沈阳' },
          { name: '振安区', cityKey: '沈阳' },
          { name: '宽甸满族自治县', cityKey: '沈阳' },
          { name: '东港市', cityKey: '沈阳' },
          { name: '凤城市', cityKey: '沈阳' },
        ],
      },
      {
        name: '锦州市',
        districts: [
          { name: '古塔区', cityKey: '沈阳' },
          { name: '凌河区', cityKey: '沈阳' },
          { name: '太和区', cityKey: '沈阳' },
          { name: '黑山县', cityKey: '沈阳' },
          { name: '义县', cityKey: '沈阳' },
          { name: '凌海市', cityKey: '沈阳' },
          { name: '北镇市', cityKey: '沈阳' },
        ],
      },
      {
        name: '营口市',
        districts: [
          { name: '站前区', cityKey: '沈阳' },
          { name: '西市区', cityKey: '沈阳' },
          { name: '鲅鱼圈区', cityKey: '沈阳' },
          { name: '老边区', cityKey: '沈阳' },
          { name: '盖州市', cityKey: '沈阳' },
          { name: '大石桥市', cityKey: '沈阳' },
        ],
      },
      {
        name: '阜新市',
        districts: [
          { name: '海州区', cityKey: '沈阳' },
          { name: '新邱区', cityKey: '沈阳' },
          { name: '太平区', cityKey: '沈阳' },
          { name: '清河门区', cityKey: '沈阳' },
          { name: '细河区', cityKey: '沈阳' },
          { name: '阜新蒙古族自治县', cityKey: '沈阳' },
          { name: '彰武县', cityKey: '沈阳' },
        ],
      },
      {
        name: '辽阳市',
        districts: [
          { name: '白塔区', cityKey: '沈阳' },
          { name: '文圣区', cityKey: '沈阳' },
          { name: '宏伟区', cityKey: '沈阳' },
          { name: '弓长岭区', cityKey: '沈阳' },
          { name: '太子河区', cityKey: '沈阳' },
          { name: '辽阳县', cityKey: '沈阳' },
          { name: '灯塔市', cityKey: '沈阳' },
        ],
      },
      {
        name: '盘锦市',
        districts: [
          { name: '双台子区', cityKey: '沈阳' },
          { name: '兴隆台区', cityKey: '沈阳' },
          { name: '大洼区', cityKey: '沈阳' },
          { name: '盘山县', cityKey: '沈阳' },
        ],
      },
      {
        name: '铁岭市',
        districts: [
          { name: '银州区', cityKey: '沈阳' },
          { name: '清河区', cityKey: '沈阳' },
          { name: '铁岭县', cityKey: '沈阳' },
          { name: '西丰县', cityKey: '沈阳' },
          { name: '昌图县', cityKey: '沈阳' },
          { name: '调兵山市', cityKey: '沈阳' },
          { name: '开原市', cityKey: '沈阳' },
        ],
      },
      {
        name: '朝阳市',
        districts: [
          { name: '双塔区', cityKey: '沈阳' },
          { name: '龙城区', cityKey: '沈阳' },
          { name: '朝阳县', cityKey: '沈阳' },
          { name: '建平县', cityKey: '沈阳' },
          { name: '喀喇沁左翼蒙古族自治县', cityKey: '沈阳' },
          { name: '北票市', cityKey: '沈阳' },
          { name: '凌源市', cityKey: '沈阳' },
        ],
      },
      {
        name: '葫芦岛市',
        districts: [
          { name: '连山区', cityKey: '沈阳' },
          { name: '龙港区', cityKey: '沈阳' },
          { name: '南票区', cityKey: '沈阳' },
          { name: '绥中县', cityKey: '沈阳' },
          { name: '建昌县', cityKey: '沈阳' },
          { name: '兴城市', cityKey: '沈阳' },
        ],
      },
    ],
  },
  {
    name: '吉林省',
    cities: [
      {
        name: '长春市',
        districts: [
          { name: '南关区', cityKey: '长春' },
          { name: '宽城区', cityKey: '长春' },
          { name: '朝阳区', cityKey: '长春' },
          { name: '二道区', cityKey: '长春' },
          { name: '绿园区', cityKey: '长春' },
          { name: '双阳区', cityKey: '长春' },
          { name: '九台区', cityKey: '长春' },
          { name: '农安县', cityKey: '长春' },
          { name: '榆树市', cityKey: '长春' },
          { name: '德惠市', cityKey: '长春' },
        ],
      },
      {
        name: '吉林市',
        districts: [
          { name: '昌邑区', cityKey: '长春' },
          { name: '龙潭区', cityKey: '长春' },
          { name: '船营区', cityKey: '长春' },
          { name: '丰满区', cityKey: '长春' },
          { name: '永吉县', cityKey: '长春' },
          { name: '蛟河市', cityKey: '长春' },
          { name: '桦甸市', cityKey: '长春' },
          { name: '舒兰市', cityKey: '长春' },
        ],
      },
    ],
  },
  {
    name: '黑龙江省',
    cities: [
      {
        name: '哈尔滨市',
        districts: [
          { name: '道里区', cityKey: '哈尔滨' },
          { name: '道外区', cityKey: '哈尔滨' },
          { name: '南岗区', cityKey: '哈尔滨' },
          { name: '香坊区', cityKey: '哈尔滨' },
          { name: '平房区', cityKey: '哈尔滨' },
          { name: '松北区', cityKey: '哈尔滨' },
          { name: '呼兰区', cityKey: '哈尔滨' },
          { name: '阿城区', cityKey: '哈尔滨' },
          { name: '双城区', cityKey: '哈尔滨' },
          { name: '依兰县', cityKey: '哈尔滨' },
          { name: '方正县', cityKey: '哈尔滨' },
        ],
      },
    ],
  },
  {
    name: '江苏省',
    cities: [
      {
        name: '南京市',
        districts: [
          { name: '玄武区', cityKey: '南京' },
          { name: '秦淮区', cityKey: '南京' },
          { name: '建邺区', cityKey: '南京' },
          { name: '鼓楼区', cityKey: '南京' },
          { name: '浦口区', cityKey: '南京' },
          { name: '栖霞区', cityKey: '南京' },
          { name: '雨花台区', cityKey: '南京' },
          { name: '江宁区', cityKey: '南京' },
          { name: '六合区', cityKey: '南京' },
          { name: '溧水区', cityKey: '南京' },
          { name: '高淳区', cityKey: '南京' },
        ],
      },
      {
        name: '苏州市',
        districts: [
          { name: '姑苏区', cityKey: '苏州' },
          { name: '虎丘区', cityKey: '苏州' },
          { name: '吴中区', cityKey: '苏州' },
          { name: '相城区', cityKey: '苏州' },
          { name: '吴江区', cityKey: '苏州' },
          { name: '常熟市', cityKey: '苏州' },
          { name: '张家港市', cityKey: '苏州' },
          { name: '昆山市', cityKey: '苏州' },
          { name: '太仓市', cityKey: '苏州' },
        ],
      },
      {
        name: '无锡市',
        districts: [
          { name: '梁溪区', cityKey: '苏州' },
          { name: '锡山区', cityKey: '苏州' },
          { name: '惠山区', cityKey: '苏州' },
          { name: '滨湖区', cityKey: '苏州' },
          { name: '新吴区', cityKey: '苏州' },
          { name: '江阴市', cityKey: '苏州' },
          { name: '宜兴市', cityKey: '苏州' },
        ],
      },
    ],
  },
  {
    name: '浙江省',
    cities: [
      {
        name: '杭州市',
        districts: [
          { name: '上城区', cityKey: '杭州' },
          { name: '下城区', cityKey: '杭州' },
          { name: '江干区', cityKey: '杭州' },
          { name: '拱墅区', cityKey: '杭州' },
          { name: '西湖区', cityKey: '杭州' },
          { name: '滨江区', cityKey: '杭州' },
          { name: '萧山区', cityKey: '杭州' },
          { name: '余杭区', cityKey: '杭州' },
          { name: '富阳区', cityKey: '杭州' },
          { name: '临安区', cityKey: '杭州' },
          { name: '桐庐县', cityKey: '杭州' },
          { name: '淳安县', cityKey: '杭州' },
          { name: '建德市', cityKey: '杭州' },
        ],
      },
      {
        name: '宁波市',
        districts: [
          { name: '海曙区', cityKey: '杭州' },
          { name: '江北区', cityKey: '杭州' },
          { name: '北仑区', cityKey: '杭州' },
          { name: '镇海区', cityKey: '杭州' },
          { name: '鄞州区', cityKey: '杭州' },
          { name: '奉化区', cityKey: '杭州' },
          { name: '象山县', cityKey: '杭州' },
          { name: '宁海县', cityKey: '杭州' },
          { name: '余姚市', cityKey: '杭州' },
          { name: '慈溪市', cityKey: '杭州' },
        ],
      },
      {
        name: '温州市',
        districts: [
          { name: '鹿城区', cityKey: '杭州' },
          { name: '龙湾区', cityKey: '杭州' },
          { name: '瓯海区', cityKey: '杭州' },
          { name: '洞头区', cityKey: '杭州' },
          { name: '永嘉县', cityKey: '杭州' },
          { name: '平阳县', cityKey: '杭州' },
          { name: '苍南县', cityKey: '杭州' },
          { name: '文成县', cityKey: '杭州' },
          { name: '泰顺县', cityKey: '杭州' },
          { name: '瑞安市', cityKey: '杭州' },
          { name: '乐清市', cityKey: '杭州' },
        ],
      },
    ],
  },
  {
    name: '安徽省',
    cities: [
      {
        name: '合肥市',
        districts: [
          { name: '瑶海区', cityKey: '合肥' },
          { name: '庐阳区', cityKey: '合肥' },
          { name: '蜀山区', cityKey: '合肥' },
          { name: '包河区', cityKey: '合肥' },
          { name: '长丰县', cityKey: '合肥' },
          { name: '肥东县', cityKey: '合肥' },
          { name: '肥西县', cityKey: '合肥' },
          { name: '庐江县', cityKey: '合肥' },
          { name: '巢湖市', cityKey: '合肥' },
        ],
      },
    ],
  },
  {
    name: '福建省',
    cities: [
      {
        name: '福州市',
        districts: [
          { name: '鼓楼区', cityKey: '福州' },
          { name: '台江区', cityKey: '福州' },
          { name: '仓山区', cityKey: '福州' },
          { name: '马尾区', cityKey: '福州' },
          { name: '晋安区', cityKey: '福州' },
          { name: '长乐区', cityKey: '福州' },
          { name: '闽侯县', cityKey: '福州' },
          { name: '连江县', cityKey: '福州' },
          { name: '罗源县', cityKey: '福州' },
          { name: '闽清县', cityKey: '福州' },
          { name: '永泰县', cityKey: '福州' },
          { name: '平潭县', cityKey: '福州' },
          { name: '福清市', cityKey: '福州' },
        ],
      },
      {
        name: '厦门市',
        districts: [
          { name: '思明区', cityKey: '福州' },
          { name: '海沧区', cityKey: '福州' },
          { name: '湖里区', cityKey: '福州' },
          { name: '集美区', cityKey: '福州' },
          { name: '同安区', cityKey: '福州' },
          { name: '翔安区', cityKey: '福州' },
        ],
      },
    ],
  },
  {
    name: '江西省',
    cities: [
      {
        name: '南昌市',
        districts: [
          { name: '东湖区', cityKey: '南昌' },
          { name: '西湖区', cityKey: '南昌' },
          { name: '青云谱区', cityKey: '南昌' },
          { name: '青山湖区', cityKey: '南昌' },
          { name: '新建区', cityKey: '南昌' },
          { name: '红谷滩区', cityKey: '南昌' },
          { name: '南昌县', cityKey: '南昌' },
          { name: '安义县', cityKey: '南昌' },
          { name: '进贤县', cityKey: '南昌' },
        ],
      },
    ],
  },
  {
    name: '山东省',
    cities: [
      {
        name: '济南市',
        districts: [
          { name: '历下区', cityKey: '济南' },
          { name: '市中区', cityKey: '济南' },
          { name: '槐荫区', cityKey: '济南' },
          { name: '天桥区', cityKey: '济南' },
          { name: '历城区', cityKey: '济南' },
          { name: '长清区', cityKey: '济南' },
          { name: '章丘区', cityKey: '济南' },
          { name: '济阳区', cityKey: '济南' },
          { name: '莱芜区', cityKey: '济南' },
          { name: '钢城区', cityKey: '济南' },
          { name: '平阴县', cityKey: '济南' },
          { name: '商河县', cityKey: '济南' },
        ],
      },
      {
        name: '青岛市',
        districts: [
          { name: '市南区', cityKey: '济南' },
          { name: '市北区', cityKey: '济南' },
          { name: '黄岛区', cityKey: '济南' },
          { name: '崂山区', cityKey: '济南' },
          { name: '李沧区', cityKey: '济南' },
          { name: '城阳区', cityKey: '济南' },
          { name: '即墨区', cityKey: '济南' },
          { name: '胶州市', cityKey: '济南' },
          { name: '平度市', cityKey: '济南' },
          { name: '莱西市', cityKey: '济南' },
        ],
      },
    ],
  },
  {
    name: '河南省',
    cities: [
      {
        name: '郑州市',
        districts: [
          { name: '中原区', cityKey: '郑州' },
          { name: '二七区', cityKey: '郑州' },
          { name: '管城回族区', cityKey: '郑州' },
          { name: '金水区', cityKey: '郑州' },
          { name: '上街区', cityKey: '郑州' },
          { name: '惠济区', cityKey: '郑州' },
          { name: '中牟县', cityKey: '郑州' },
          { name: '巩义市', cityKey: '郑州' },
          { name: '荥阳市', cityKey: '郑州' },
          { name: '新密市', cityKey: '郑州' },
          { name: '新郑市', cityKey: '郑州' },
          { name: '登封市', cityKey: '郑州' },
        ],
      },
    ],
  },
  {
    name: '湖北省',
    cities: [
      {
        name: '武汉市',
        districts: [
          { name: '江岸区', cityKey: '武汉' },
          { name: '江汉区', cityKey: '武汉' },
          { name: '硚口区', cityKey: '武汉' },
          { name: '汉阳区', cityKey: '武汉' },
          { name: '武昌区', cityKey: '武汉' },
          { name: '青山区', cityKey: '武汉' },
          { name: '洪山区', cityKey: '武汉' },
          { name: '东西湖区', cityKey: '武汉' },
          { name: '蔡甸区', cityKey: '武汉' },
          { name: '江夏区', cityKey: '武汉' },
          { name: '黄陂区', cityKey: '武汉' },
          { name: '新洲区', cityKey: '武汉' },
          { name: '汉南区', cityKey: '武汉' },
        ],
      },
    ],
  },
  {
    name: '湖南省',
    cities: [
      {
        name: '长沙市',
        districts: [
          { name: '芙蓉区', cityKey: '长沙' },
          { name: '天心区', cityKey: '长沙' },
          { name: '岳麓区', cityKey: '长沙' },
          { name: '开福区', cityKey: '长沙' },
          { name: '雨花区', cityKey: '长沙' },
          { name: '望城区', cityKey: '长沙' },
          { name: '长沙县', cityKey: '长沙' },
          { name: '浏阳市', cityKey: '长沙' },
          { name: '宁乡市', cityKey: '长沙' },
        ],
      },
    ],
  },
  {
    name: '广东省',
    cities: [
      {
        name: '广州市',
        districts: [
          { name: '荔湾区', cityKey: '广州' },
          { name: '越秀区', cityKey: '广州' },
          { name: '海珠区', cityKey: '广州' },
          { name: '天河区', cityKey: '广州' },
          { name: '白云区', cityKey: '广州' },
          { name: '黄埔区', cityKey: '广州' },
          { name: '番禺区', cityKey: '广州' },
          { name: '花都区', cityKey: '广州' },
          { name: '南沙区', cityKey: '广州' },
          { name: '从化区', cityKey: '广州' },
          { name: '增城区', cityKey: '广州' },
        ],
      },
      {
        name: '深圳市',
        districts: [
          { name: '罗湖区', cityKey: '深圳' },
          { name: '福田区', cityKey: '深圳' },
          { name: '南山区', cityKey: '深圳' },
          { name: '宝安区', cityKey: '深圳' },
          { name: '龙岗区', cityKey: '深圳' },
          { name: '盐田区', cityKey: '深圳' },
          { name: '光明区', cityKey: '深圳' },
          { name: '坪山区', cityKey: '深圳' },
          { name: '龙华区', cityKey: '深圳' },
          { name: '大鹏新区', cityKey: '深圳' },
        ],
      },
      {
        name: '东莞市',
        districts: [
          { name: '莞城街道', cityKey: '广州' },
          { name: '南城街道', cityKey: '广州' },
          { name: '东城街道', cityKey: '广州' },
          { name: '万江街道', cityKey: '广州' },
          { name: '厚街镇', cityKey: '广州' },
          { name: '长安镇', cityKey: '广州' },
          { name: '虎门镇', cityKey: '广州' },
          { name: '塘厦镇', cityKey: '广州' },
        ],
      },
      {
        name: '佛山市',
        districts: [
          { name: '禅城区', cityKey: '广州' },
          { name: '南海区', cityKey: '广州' },
          { name: '顺德区', cityKey: '广州' },
          { name: '三水区', cityKey: '广州' },
          { name: '高明区', cityKey: '广州' },
        ],
      },
    ],
  },
  {
    name: '广西壮族自治区',
    cities: [
      {
        name: '南宁市',
        districts: [
          { name: '兴宁区', cityKey: '南宁' },
          { name: '青秀区', cityKey: '南宁' },
          { name: '江南区', cityKey: '南宁' },
          { name: '西乡塘区', cityKey: '南宁' },
          { name: '良庆区', cityKey: '南宁' },
          { name: '邕宁区', cityKey: '南宁' },
          { name: '武鸣区', cityKey: '南宁' },
          { name: '隆安县', cityKey: '南宁' },
          { name: '马山县', cityKey: '南宁' },
          { name: '上林县', cityKey: '南宁' },
          { name: '宾阳县', cityKey: '南宁' },
          { name: '横州市', cityKey: '南宁' },
        ],
      },
    ],
  },
  {
    name: '海南省',
    cities: [
      {
        name: '海口市',
        districts: [
          { name: '秀英区', cityKey: '海口' },
          { name: '龙华区', cityKey: '海口' },
          { name: '琼山区', cityKey: '海口' },
          { name: '美兰区', cityKey: '海口' },
        ],
      },
      {
        name: '三亚市',
        districts: [
          { name: '海棠区', cityKey: '海口' },
          { name: '吉阳区', cityKey: '海口' },
          { name: '天涯区', cityKey: '海口' },
          { name: '崖州区', cityKey: '海口' },
        ],
      },
    ],
  },
  {
    name: '四川省',
    cities: [
      {
        name: '成都市',
        districts: [
          { name: '锦江区', cityKey: '成都' },
          { name: '青羊区', cityKey: '成都' },
          { name: '金牛区', cityKey: '成都' },
          { name: '武侯区', cityKey: '成都' },
          { name: '成华区', cityKey: '成都' },
          { name: '龙泉驿区', cityKey: '成都' },
          { name: '青白江区', cityKey: '成都' },
          { name: '新都区', cityKey: '成都' },
          { name: '温江区', cityKey: '成都' },
          { name: '双流区', cityKey: '成都' },
          { name: '郫都区', cityKey: '成都' },
          { name: '新津区', cityKey: '成都' },
          { name: '金堂县', cityKey: '成都' },
          { name: '大邑县', cityKey: '成都' },
          { name: '蒲江县', cityKey: '成都' },
          { name: '都江堰市', cityKey: '成都' },
          { name: '彭州市', cityKey: '成都' },
          { name: '邛崃市', cityKey: '成都' },
          { name: '崇州市', cityKey: '成都' },
          { name: '简阳市', cityKey: '成都' },
        ],
      },
    ],
  },
  {
    name: '贵州省',
    cities: [
      {
        name: '贵阳市',
        districts: [
          { name: '南明区', cityKey: '贵阳' },
          { name: '云岩区', cityKey: '贵阳' },
          { name: '花溪区', cityKey: '贵阳' },
          { name: '乌当区', cityKey: '贵阳' },
          { name: '白云区', cityKey: '贵阳' },
          { name: '观山湖区', cityKey: '贵阳' },
          { name: '开阳县', cityKey: '贵阳' },
          { name: '息烽县', cityKey: '贵阳' },
          { name: '修文县', cityKey: '贵阳' },
          { name: '清镇市', cityKey: '贵阳' },
        ],
      },
    ],
  },
  {
    name: '云南省',
    cities: [
      {
        name: '昆明市',
        districts: [
          { name: '五华区', cityKey: '昆明' },
          { name: '盘龙区', cityKey: '昆明' },
          { name: '官渡区', cityKey: '昆明' },
          { name: '西山区', cityKey: '昆明' },
          { name: '东川区', cityKey: '昆明' },
          { name: '呈贡区', cityKey: '昆明' },
          { name: '晋宁区', cityKey: '昆明' },
          { name: '富民县', cityKey: '昆明' },
          { name: '宜良县', cityKey: '昆明' },
          { name: '石林彝族自治县', cityKey: '昆明' },
          { name: '嵩明县', cityKey: '昆明' },
          { name: '安宁市', cityKey: '昆明' },
        ],
      },
    ],
  },
  {
    name: '陕西省',
    cities: [
      {
        name: '西安市',
        districts: [
          { name: '新城区', cityKey: '西安' },
          { name: '碑林区', cityKey: '西安' },
          { name: '莲湖区', cityKey: '西安' },
          { name: '灞桥区', cityKey: '西安' },
          { name: '未央区', cityKey: '西安' },
          { name: '雁塔区', cityKey: '西安' },
          { name: '阎良区', cityKey: '西安' },
          { name: '临潼区', cityKey: '西安' },
          { name: '长安区', cityKey: '西安' },
          { name: '高陵区', cityKey: '西安' },
          { name: '鄠邑区', cityKey: '西安' },
          { name: '蓝田县', cityKey: '西安' },
          { name: '周至县', cityKey: '西安' },
        ],
      },
    ],
  },
  {
    name: '甘肃省',
    cities: [
      {
        name: '兰州市',
        districts: [
          { name: '城关区', cityKey: '兰州' },
          { name: '七里河区', cityKey: '兰州' },
          { name: '西固区', cityKey: '兰州' },
          { name: '安宁区', cityKey: '兰州' },
          { name: '红古区', cityKey: '兰州' },
          { name: '永登县', cityKey: '兰州' },
          { name: '皋兰县', cityKey: '兰州' },
          { name: '榆中县', cityKey: '兰州' },
        ],
      },
    ],
  },
  {
    name: '青海省',
    cities: [
      {
        name: '西宁市',
        districts: [
          { name: '城东区', cityKey: '西宁' },
          { name: '城中区', cityKey: '西宁' },
          { name: '城西区', cityKey: '西宁' },
          { name: '城北区', cityKey: '西宁' },
          { name: '湟中区', cityKey: '西宁' },
          { name: '大通回族土族自治县', cityKey: '西宁' },
          { name: '湟源县', cityKey: '西宁' },
        ],
      },
    ],
  },
  {
    name: '宁夏回族自治区',
    cities: [
      {
        name: '银川市',
        districts: [
          { name: '兴庆区', cityKey: '银川' },
          { name: '西夏区', cityKey: '银川' },
          { name: '金凤区', cityKey: '银川' },
          { name: '永宁县', cityKey: '银川' },
          { name: '贺兰县', cityKey: '银川' },
          { name: '灵武市', cityKey: '银川' },
        ],
      },
    ],
  },
  {
    name: '新疆维吾尔自治区',
    cities: [
      {
        name: '乌鲁木齐市',
        districts: [
          { name: '天山区', cityKey: '乌鲁木齐' },
          { name: '沙依巴克区', cityKey: '乌鲁木齐' },
          { name: '新市区', cityKey: '乌鲁木齐' },
          { name: '水磨沟区', cityKey: '乌鲁木齐' },
          { name: '头屯河区', cityKey: '乌鲁木齐' },
          { name: '达坂城区', cityKey: '乌鲁木齐' },
          { name: '米东区', cityKey: '乌鲁木齐' },
          { name: '乌鲁木齐县', cityKey: '乌鲁木齐' },
        ],
      },
    ],
  },
  {
    name: '内蒙古自治区',
    cities: [
      {
        name: '呼和浩特市',
        districts: [
          { name: '回民区', cityKey: '呼和浩特' },
          { name: '玉泉区', cityKey: '呼和浩特' },
          { name: '赛罕区', cityKey: '呼和浩特' },
          { name: '新城区', cityKey: '呼和浩特' },
          { name: '土默特左旗', cityKey: '呼和浩特' },
          { name: '托克托县', cityKey: '呼和浩特' },
          { name: '和林格尔县', cityKey: '呼和浩特' },
          { name: '清水河县', cityKey: '呼和浩特' },
          { name: '武川县', cityKey: '呼和浩特' },
        ],
      },
    ],
  },
  {
    name: '西藏自治区',
    cities: [
      {
        name: '拉萨市',
        districts: [
          { name: '城关区', cityKey: '拉萨' },
          { name: '堆龙德庆区', cityKey: '拉萨' },
          { name: '达孜区', cityKey: '拉萨' },
          { name: '林周县', cityKey: '拉萨' },
          { name: '当雄县', cityKey: '拉萨' },
          { name: '尼木县', cityKey: '拉萨' },
          { name: '曲水县', cityKey: '拉萨' },
          { name: '墨竹工卡县', cityKey: '拉萨' },
        ],
      },
    ],
  },
];
